CREATE TABLE POST_BD_INFO
(
  BD_SEQ CHAR(25) PRIMARY KEY NOT NULL,
  LEGAL_DONG_CD CHAR(10),
  SIDO_NM VARCHAR(40),
  SIGUNGU_NM VARCHAR(40),
  LEGAL_DONG_NM VARCHAR(40),
  LEGAL_RI_NM VARCHAR(40),
  SAN_YN CHAR(1),
  LOT_BASIC_NUM INT(4),
  LOT_PART_NUM INT(4),
  ROAD_CD CHAR(12),
  ROAD_NM VARCHAR(80),
  UNDER_YN CHAR(1),
  BD_BASIC_NUM INT(5),
  BD_PART_NUM INT(5),
  POST_CD CHAR(5),
  SIGUNGU_BD_NM VARCHAR(200),
  JOINT_YN CHAR(1),
  BASE_AREA_NUM CHAR(5)
);
CREATE TABLE POST_REF_LOT
(
  ROAD_CD CHAR(12) NOT NULL,
  UNDER_YN CHAR(1),
  BD_BASIC_NUM INT(5),
  BD_PART_NUM INT(5),
  LOT_SEQ INT(10),
  LEGAL_DONG_CD CHAR(10),
  SIDO_NM VARCHAR(40),
  SIGUNGU_NM VARCHAR(40),
  LEGAL_DONG_NM VARCHAR(40),
  LEGAL_RI_NM VARCHAR(40),
  SAN_YN CHAR(1),
  LOT_BASIC_NUM INT(4),
  LOT_PART_NUM INT(4)
);


SELECT * FROM POST_BD_INFO;